version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: pokemon_review
      MYSQL_USER: axios
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql